### ISSUE TITLE
Merge latest Beta to Releases for Windows

### ISSUE THREAD

**Issue by githubllff** [AndreasSko/go-jwlm#142]
Dear Andreas. Pleased to see a way that we can still merge our backup files. Is there any chance you can release a binary of your latest so we can use in windows? Tx so much

**Comment by AndreasSko** [comment]
Ah, sorry for that. The build job is currently broken, so unfortunately the new CLI version wasn‘t released yet. I‘m trying to fix that over the next few days 🙂

**Comment by githubllff** [comment]
Thanks so much. Great to see this will still work with the version 14

**Comment by AndreasSko** [comment]
@githubllff the CLI version should be released now 🙂

**Comment by githubllff** [comment]
Thanks Andreas. I used it last night as an attempt to replace jwlmerge. Unfortunately it doesnt seem to merge two backups correctly. It seems to import highlights and notes up to a certain point and then stop. If you want me to PM you somehow the two backup files and the result of the merge let me know. Thanks so much

**Comment by AndreasSko** [comment]
Oh, that doesn’t sound too good 😅 Yeah, if it’s ok for you to provide me with the backups that would be great. You can send them to me via email at jwlm@andreas-sk.de
